name: Manual workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: mountstuff
      run: |
        mkdir -p lfs/{dev,proc,sys,run}
        mount --bind /dev lfs/dev
        mount --bind /proc lfs/proc
        mount --bind /sys lfs/sys
        mount --bind /run lfs/run
    - name: dockerbuild
      uses: ./docker
