name: Manual workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: mountstuff
      run: |
        mkdir -p lfs/{dev,proc,sys,run}
        sudo mount --bind /dev lfs/dev
        sudo mount --bind /dev/pts lfs/dev/pts
        sudo mount --bind /proc lfs/proc
        sudo mount --bind /sys lfs/sys
        sudo mount --bind /run lfs/run
    - name: dockerbuild
      uses: ./docker
